
version: "3.1"
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            docker: "true"
        env_file:
            - ./docker-compose.env
        expose:
            - 5432
        ports:
            - 5433:5432
        volumes:
            - ~/opt/docker-data/postgresSQL:/var/lib/postgresql/data
        networks:
          - postgres

networks:
    postgres:
        external: true
