services:
  postgres:
    image: postgres:15-alpine
    container_name: container_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pgsql
    ports:
      - 5433:5432
    volumes:
      - /Users/caveliermickael/opt/docker-data/postgresSQL:/var/lib/postgresql/data
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  postgres:
    external: true
